// Deterministic offline bundle. Run after changing PNG/audio files; no npm dependencies.
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const ctx = vm.createContext({});
vm.runInContext(fs.readFileSync(path.join(root, 'src/gfx/ArtAssets.js'), 'utf8') + '\nthis.art = ArtAssets;', ctx);
const files = [...new Set(ctx.art.images.map(a => a.url)), 'assets/鹦鹉穿风.mp3',
  ...['点击.mp3', '受伤.ogg', '失败.mp3', '收集绿宝石.mp3', 'man.mp3'].map(f => 'assets/样板音效/' + f)].sort();
const mime = {'.png':'image/png', '.mp3':'audio/mpeg', '.ogg':'audio/ogg'};
const assets = Object.fromEntries(files.map(file => [file,
  'data:' + mime[path.extname(file)] + ';base64,' + fs.readFileSync(path.join(root, file)).toString('base64')]));
const result = '// Generated by node tools/pack-assets.cjs; do not edit.\nwindow.GAME_ASSETS = ' + JSON.stringify(assets) + ';\n';
const destination = path.join(root, 'assets/offline.js');
if (process.argv.includes('--check')) {
  if (!fs.existsSync(destination) || fs.readFileSync(destination, 'utf8') !== result) {
    throw Error('Offline bundle is stale. Run node tools/pack-assets.cjs');
  }
} else fs.writeFileSync(destination, result);
console.log(`${files.length} offline assets verified (${(Buffer.byteLength(result)/1024/1024).toFixed(2)} MiB)`);
